### ISSUE TITLE
ERROR TaxPhlAn-SLST-Design-wrapper.py [mcxIOopen] 

### ISSUE THREAD

**Issue by koogura001** [ederveen/taxphlan#1]
"[mcxIOopen] r stream <... /... /Docker/TaxPhlAn-WORKDIR/my-directory/OrthAgogue_OUT/all.abc> cannae be opened" error. How do I resolve this?

> (7) Performing phylogenetic calculations, building trees ...
> 	RUNNING: orthAgogue -i /Docker/TaxPhlAn-WORKDIR/my-directory/BLAST_OUT/blast_allvall.out -t 0 -p 1 -e 6 -O ./ -s '_'
> 	RUNNING: mcl ../../Docker/TaxPhlAn-WORKDIR/my-directory/OrthAgogue_OUT/all.abc --abc -I 1.5 -o ../../Docker/TaxPhlAn-WORKDIR/my-directory/PhyloTree_OUT/mclAll.out
> 
> ERROR TaxPhlAn-SLST-Design-wrapper.py:
> ___ [mcxIOopen] r stream <../../Docker/TaxPhlAn-WORKDIR/my-directory/OrthAgogue_OUT/all.abc> cannae be opened

**Comment by ederveen** [comment]
The problem might be path-related, from where (which directory) do you run this command? 
You could try to run with full path instead of the `../../Docker/` path, the `../` might cause issues later on in the script paths.

edit : and for similar reasons, also provide full path references for the argument values you provide to the wrapper script

**Comment by koogura001** [comment]
It worked! 
Thank you very much for your help, Tom.
