### ISSUE TITLE
Migrating TaxPhlAn -> Singularity

### ISSUE THREAD

**Issue by akp1d12** [ederveen/taxphlan#2]
Dear Dr Ederveen,
                             I'm trying to containerise TaxPhlAn for use with Singularity on our HPC. I've built an interactive sandbox (called TAX_SAND) of the TaxPhlAn docker image and replaced tbl2asn module but am having trouble running the Docker-initialise.py and start taxphlan.sh scripts since they require Docker. 

When i run the following test command 
singularity run -B ${PWD}/Docker:${PWD} ./TaxPhlAn/Pipeline-Design/TaxPhlAn-SLST-Design-wrapper.py --indir Test-data/indir-genomes-BIF/ --conf Test-data/config.txt --outdir 

I get the following error
FATAL:   While checking container encryption: could not open image /home/anish/Singularity_TAXPHYLAN/TAX_SAND/TaxPhlAn/Pipeline-Design/TaxPhlAn-SLST-Design-wrapper.py: image format not recognized

Could you suggest any workaround for this?
NB. I could not get singularity to list a "container ID" for the singularity SIF conversion of Docker. If that's relevant to this issue

Thank you so much

Anish

**Comment by ederveen** [comment]
Dear Anish, @akp1d12,

Thank you for your question, and apologies for my late reply, I did not received a notification.

Happy to hear your efforts on the containerisation of TaxPhlAn for Singularity. 
I have no experience with Singularity, but I do believe there is an option from them to convert a Docker container to Singularity container. I think that might be the best way to go forward? 

Note that the Start and Initiation scripts are only for simple deployment, the only thing you really need is to download the container, run the container (and mount a directory by specifying in the same run command), and use the docker exec command as provided in the Readme to 'move into the container' in order to run the scripts (i.e., I have not yet used the Docker image to run from outside of the container, but I assume that should also work). 
Perhaps it is an idea to first try to run the Docker without these Start and Initiation scripts? So that you understand what is needed to correctly run and use the Docker image, and that you try to replicate that with Singularity after converting the image to Singularity.

Let me know how it goes and happy to think along.
Best,
Tom

**Comment by ederveen** [comment]
I have not heard back, hope it has been solved by now. 
Send me a PM if you need further assistance, or (re)open a new issue.
Best
